### PR TITLE
Add days variant to get

### PR DESCRIPTION
**Pull request by zrebcu411**
Added `` `date`` variant to `get` which returns a day of month ( `` `day`` returns a day of week).
@Jimexist

### CODE REVIEW

**Comment by Anahkiasen** [comment]
I feel like that's not the only problem, currently `Moment.day` and Moment.weekday` both return the same thing:

```reason
let currentDate = momentNow();
Js.log3(
  Moment.format("YYYY-MM-DD", currentDate), /* 2018-11-17 */
  Moment.day(currentDate), /* 6 */
  Moment.weekday(currentDate), /* 6 */
);
```

Should the `.day` call not return 17?

**Comment by Jimexist** [comment]
@Anahkiasen I feel that this should be reported to moment.js itself, this is only a wrapper. there's little risk in adding one more wrapper

**Comment by Jimexist** [comment]
@Anahkiasen I feel that this should be reported to moment.js itself, this is only a wrapper. there's little risk in adding one more wrapper

**Comment by Anahkiasen** [comment]
@Jimexist You're correct it seems this is also the case in the native library, my bad. In my head day and weekday were two different properties 😅

**Comment by liubko** [comment]
can this change be included in `0.3.3`, please?

**Pull request merged**
